// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgID 定义了所有可能的消息类型
type MsgID int32

const (
	MsgID_MsgID_UNKNOWN MsgID = 0
	// Auth & Account
	MsgID_MsgID_REGISTER_REQ MsgID = 1001
	MsgID_MsgID_REGISTER_RSP MsgID = 1002
	MsgID_MsgID_LOGIN_REQ    MsgID = 1003
	MsgID_MsgID_LOGIN_RSP    MsgID = 1004
	// Game Logic
	MsgID_MsgID_ECHO_REQ          MsgID = 2001 // 用于压测测试的简单Echo
	MsgID_MsgID_ECHO_RSP          MsgID = 2002
	MsgID_MsgID_GET_USER_INFO_REQ MsgID = 2003
	MsgID_MsgID_GET_USER_INFO_RSP MsgID = 2004
	// Backpack
	MsgID_MsgID_GET_ITEM_REQ     MsgID = 3001
	MsgID_MsgID_GET_ITEM_RSP     MsgID = 3002
	MsgID_MsgID_DISCARD_ITEM_REQ MsgID = 3003
	MsgID_MsgID_DISCARD_ITEM_RSP MsgID = 3004
)

// Enum value maps for MsgID.
var (
	MsgID_name = map[int32]string{
		0:    "MsgID_UNKNOWN",
		1001: "MsgID_REGISTER_REQ",
		1002: "MsgID_REGISTER_RSP",
		1003: "MsgID_LOGIN_REQ",
		1004: "MsgID_LOGIN_RSP",
		2001: "MsgID_ECHO_REQ",
		2002: "MsgID_ECHO_RSP",
		2003: "MsgID_GET_USER_INFO_REQ",
		2004: "MsgID_GET_USER_INFO_RSP",
		3001: "MsgID_GET_ITEM_REQ",
		3002: "MsgID_GET_ITEM_RSP",
		3003: "MsgID_DISCARD_ITEM_REQ",
		3004: "MsgID_DISCARD_ITEM_RSP",
	}
	MsgID_value = map[string]int32{
		"MsgID_UNKNOWN":           0,
		"MsgID_REGISTER_REQ":      1001,
		"MsgID_REGISTER_RSP":      1002,
		"MsgID_LOGIN_REQ":         1003,
		"MsgID_LOGIN_RSP":         1004,
		"MsgID_ECHO_REQ":          2001,
		"MsgID_ECHO_RSP":          2002,
		"MsgID_GET_USER_INFO_REQ": 2003,
		"MsgID_GET_USER_INFO_RSP": 2004,
		"MsgID_GET_ITEM_REQ":      3001,
		"MsgID_GET_ITEM_RSP":      3002,
		"MsgID_DISCARD_ITEM_REQ":  3003,
		"MsgID_DISCARD_ITEM_RSP":  3004,
	}
)

func (x MsgID) Enum() *MsgID {
	p := new(MsgID)
	*p = x
	return p
}

func (x MsgID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgID) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_msg_proto_enumTypes[0].Descriptor()
}

func (MsgID) Type() protoreflect.EnumType {
	return &file_proto_msg_proto_enumTypes[0]
}

func (x MsgID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgID.Descriptor instead.
func (MsgID) EnumDescriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{0}
}

// 物品结构
type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Item) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 获取道具
type GetItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemType      int32                  `protobuf:"varint,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemReq) Reset() {
	*x = GetItemReq{}
	mi := &file_proto_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemReq) ProtoMessage() {}

func (x *GetItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemReq.ProtoReflect.Descriptor instead.
func (*GetItemReq) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemReq) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *GetItemReq) GetItemType() int32 {
	if x != nil {
		return x.ItemType
	}
	return 0
}

func (x *GetItemReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetItemRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRsp) Reset() {
	*x = GetItemRsp{}
	mi := &file_proto_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRsp) ProtoMessage() {}

func (x *GetItemRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRsp.ProtoReflect.Descriptor instead.
func (*GetItemRsp) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{2}
}

func (x *GetItemRsp) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

// 扔掉道具
type DiscardItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemType      int32                  `protobuf:"varint,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscardItemReq) Reset() {
	*x = DiscardItemReq{}
	mi := &file_proto_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscardItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardItemReq) ProtoMessage() {}

func (x *DiscardItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardItemReq.ProtoReflect.Descriptor instead.
func (*DiscardItemReq) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{3}
}

func (x *DiscardItemReq) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *DiscardItemReq) GetItemType() int32 {
	if x != nil {
		return x.ItemType
	}
	return 0
}

func (x *DiscardItemReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DiscardItemRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscardItemRsp) Reset() {
	*x = DiscardItemRsp{}
	mi := &file_proto_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscardItemRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardItemRsp) ProtoMessage() {}

func (x *DiscardItemRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardItemRsp.ProtoReflect.Descriptor instead.
func (*DiscardItemRsp) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{4}
}

func (x *DiscardItemRsp) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

// 基础响应结构 (常用于 HTTP API 的通用返回)
type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 0表示成功，非0表示错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_proto_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{5}
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 注册请求
type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 明文或前端hash后的密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_proto_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRsp) Reset() {
	*x = RegisterRsp{}
	mi := &file_proto_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRsp) ProtoMessage() {}

func (x *RegisterRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRsp.ProtoReflect.Descriptor instead.
func (*RegisterRsp) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterRsp) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RegisterRsp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 登录请求
type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_proto_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{8}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // JWT Token，用于后续HTTP请求或TCP断线重连
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRsp) Reset() {
	*x = LoginRsp{}
	mi := &file_proto_msg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRsp) ProtoMessage() {}

func (x *LoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRsp.ProtoReflect.Descriptor instead.
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{9}
}

func (x *LoginRsp) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *LoginRsp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginRsp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 测试/压测用的Echo消息
type EchoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 用于计算延迟
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoReq) Reset() {
	*x = EchoReq{}
	mi := &file_proto_msg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoReq) ProtoMessage() {}

func (x *EchoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoReq.ProtoReflect.Descriptor instead.
func (*EchoReq) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{10}
}

func (x *EchoReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EchoReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type EchoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 原样返回，方便客户端计算RTT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRsp) Reset() {
	*x = EchoRsp{}
	mi := &file_proto_msg_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRsp) ProtoMessage() {}

func (x *EchoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRsp.ProtoReflect.Descriptor instead.
func (*EchoRsp) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{11}
}

func (x *EchoRsp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EchoRsp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 获取用户信息
type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 如果为空，则获取当前token对应用户
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_proto_msg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserInfoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserInfoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	RegisterTime  int64                  `protobuf:"varint,4,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRsp) Reset() {
	*x = GetUserInfoRsp{}
	mi := &file_proto_msg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRsp) ProtoMessage() {}

func (x *GetUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRsp.ProtoReflect.Descriptor instead.
func (*GetUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserInfoRsp) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetUserInfoRsp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserInfoRsp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserInfoRsp) GetRegisterTime() int64 {
	if x != nil {
		return x.RegisterTime
	}
	return 0
}

var File_proto_msg_proto protoreflect.FileDescriptor

const file_proto_msg_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/msg.proto\x12\x02pb\"@\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"X\n" +
	"\n" +
	"GetItemReq\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x1b\n" +
	"\titem_type\x18\x02 \x01(\x05R\bitemType\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"2\n" +
	"\n" +
	"GetItemRsp\x12$\n" +
	"\x04base\x18\x01 \x01(\v2\x10.pb.BaseResponseR\x04base\"\\\n" +
	"\x0eDiscardItemReq\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x1b\n" +
	"\titem_type\x18\x02 \x01(\x05R\bitemType\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"6\n" +
	"\x0eDiscardItemRsp\x12$\n" +
	"\x04base\x18\x01 \x01(\v2\x10.pb.BaseResponseR\x04base\"<\n" +
	"\fBaseResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"L\n" +
	"\vRegisterRsp\x12$\n" +
	"\x04base\x18\x01 \x01(\v2\x10.pb.BaseResponseR\x04base\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"_\n" +
	"\bLoginRsp\x12$\n" +
	"\x04base\x18\x01 \x01(\v2\x10.pb.BaseResponseR\x04base\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"A\n" +
	"\aEchoReq\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"A\n" +
	"\aEchoRsp\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\")\n" +
	"\x0eGetUserInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x90\x01\n" +
	"\x0eGetUserInfoRsp\x12$\n" +
	"\x04base\x18\x01 \x01(\v2\x10.pb.BaseResponseR\x04base\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12#\n" +
	"\rregister_time\x18\x04 \x01(\x03R\fregisterTime*\xca\x02\n" +
	"\x05MsgID\x12\x11\n" +
	"\rMsgID_UNKNOWN\x10\x00\x12\x17\n" +
	"\x12MsgID_REGISTER_REQ\x10\xe9\a\x12\x17\n" +
	"\x12MsgID_REGISTER_RSP\x10\xea\a\x12\x14\n" +
	"\x0fMsgID_LOGIN_REQ\x10\xeb\a\x12\x14\n" +
	"\x0fMsgID_LOGIN_RSP\x10\xec\a\x12\x13\n" +
	"\x0eMsgID_ECHO_REQ\x10\xd1\x0f\x12\x13\n" +
	"\x0eMsgID_ECHO_RSP\x10\xd2\x0f\x12\x1c\n" +
	"\x17MsgID_GET_USER_INFO_REQ\x10\xd3\x0f\x12\x1c\n" +
	"\x17MsgID_GET_USER_INFO_RSP\x10\xd4\x0f\x12\x17\n" +
	"\x12MsgID_GET_ITEM_REQ\x10\xb9\x17\x12\x17\n" +
	"\x12MsgID_GET_ITEM_RSP\x10\xba\x17\x12\x1b\n" +
	"\x16MsgID_DISCARD_ITEM_REQ\x10\xbb\x17\x12\x1b\n" +
	"\x16MsgID_DISCARD_ITEM_RSP\x10\xbc\x17B\x17Z\x15k6-game-test/proto/pbb\x06proto3"

var (
	file_proto_msg_proto_rawDescOnce sync.Once
	file_proto_msg_proto_rawDescData []byte
)

func file_proto_msg_proto_rawDescGZIP() []byte {
	file_proto_msg_proto_rawDescOnce.Do(func() {
		file_proto_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_msg_proto_rawDesc), len(file_proto_msg_proto_rawDesc)))
	})
	return file_proto_msg_proto_rawDescData
}

var file_proto_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_msg_proto_goTypes = []any{
	(MsgID)(0),             // 0: pb.MsgID
	(*Item)(nil),           // 1: pb.Item
	(*GetItemReq)(nil),     // 2: pb.GetItemReq
	(*GetItemRsp)(nil),     // 3: pb.GetItemRsp
	(*DiscardItemReq)(nil), // 4: pb.DiscardItemReq
	(*DiscardItemRsp)(nil), // 5: pb.DiscardItemRsp
	(*BaseResponse)(nil),   // 6: pb.BaseResponse
	(*RegisterReq)(nil),    // 7: pb.RegisterReq
	(*RegisterRsp)(nil),    // 8: pb.RegisterRsp
	(*LoginReq)(nil),       // 9: pb.LoginReq
	(*LoginRsp)(nil),       // 10: pb.LoginRsp
	(*EchoReq)(nil),        // 11: pb.EchoReq
	(*EchoRsp)(nil),        // 12: pb.EchoRsp
	(*GetUserInfoReq)(nil), // 13: pb.GetUserInfoReq
	(*GetUserInfoRsp)(nil), // 14: pb.GetUserInfoRsp
}
var file_proto_msg_proto_depIdxs = []int32{
	6, // 0: pb.GetItemRsp.base:type_name -> pb.BaseResponse
	6, // 1: pb.DiscardItemRsp.base:type_name -> pb.BaseResponse
	6, // 2: pb.RegisterRsp.base:type_name -> pb.BaseResponse
	6, // 3: pb.LoginRsp.base:type_name -> pb.BaseResponse
	6, // 4: pb.GetUserInfoRsp.base:type_name -> pb.BaseResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_msg_proto_init() }
func file_proto_msg_proto_init() {
	if File_proto_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_msg_proto_rawDesc), len(file_proto_msg_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_msg_proto_goTypes,
		DependencyIndexes: file_proto_msg_proto_depIdxs,
		EnumInfos:         file_proto_msg_proto_enumTypes,
		MessageInfos:      file_proto_msg_proto_msgTypes,
	}.Build()
	File_proto_msg_proto = out.File
	file_proto_msg_proto_goTypes = nil
	file_proto_msg_proto_depIdxs = nil
}
